instagram/post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^delete/(?P<post_pk>\d+)/$', views.post_delete, name='post_delete'),
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
    url(r'^comment/delete/(?P<comment_pk>\d+)/$', views.comment_delete, name='comment_delete'),
    url(r'^(?P<post_pk>\d+)/like_toggle/$', views.post_like_toggle, name='post_like_toggle'),
]

instagram/sms/urls.py
from django.conf.urls import url

from . import apis

urlpatterns = [
    url(r'^send-sms/$', apis.SendSMS.as_view(), name='sms'),
]

instagram/post/models.py
from django.conf import settings
from django.db import models


class PostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(author__isnull=True)


class Post(models.Model):
    photo = models.ImageField(upload_to='post')
    created_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL)

    # 새로만든 PostManager를 기본 모델 매니저인 objects를 대신해서 사용
    objects = PostManager()

    class Meta:
        ordering = ['-created_date', ]

    def __str__(self):
        return f'Post (PK: {self.pk})'


class PostComment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['-created_date', ]

    def __str__(self):
        return f"{self.post.pk} - {self.content}"

instagram/post/forms.py
from django import forms

from .models import Post, PostComment


class PostForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['author'].required = True

    class Meta:
        model = Post
        fields = ('photo',)
        widgets = {
            'photo': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }

    def save(self, commit=True, *args, **kwargs):
        if not self.instance.pk and commit:
            author = kwargs.pop('author', None)
            if not author:
                raise ValueError('Author field is required')
            self.instance.author = author
        return super().save(*args, **kwargs)


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ('content',)
        widgets = {
            'content': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }

instagram/config/urls/views.py
from django.conf.urls import url, include
from django.contrib import admin

from config import views
from member.urls import views as member_urls
from member.apis import FacebookLogin
from post.urls import views as post_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^post/', include(post_urls, namespace='post')),
    url(r'^member/', include(member_urls, namespace='member')),
    url(r'^facebook-login/$', FacebookLogin.as_view(), name='api-facebook'),

]

instagram/post/urls/views.py
from django.conf.urls import url

from .. import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^delete/(?P<post_pk>\d+)/$', views.post_delete, name='post_delete'),
    url(r'^(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
    url(r'^comment/delete/(?P<comment_pk>\d+)/$', views.comment_delete, name='comment_delete'),
    url(r'^(?P<post_pk>\d+)/like_toggle/$', views.post_like_toggle, name='like_toggle'),
]

instagram/post/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404

from member.decorators import login_required
from .forms import PostForm, PostCommentForm
from .models import Post, PostComment


def post_list(request):
    # posts = Post.objects.all().exclude(author__isnull=True)
    posts = Post.objects.all()
    context = {
        "posts": posts,
        "comment_form": PostCommentForm,
    }
    return render(request, 'post/post_list.html', context)
    # return render(request, 'post/index.html', context)


@login_required
def post_create(request):
    # if not request.user.is_authenticated:
    #     return redirect('member:login')
    if request.method == 'POST':
        # POST요청의 경우 PostForm인스턴스 생성과정에서 request.POST, request.FILES를 사용
        form = PostForm(request.POST, request.FILES)
        # form이 valid한지 검사
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:post_list')
    else:
        # GET요청의 경우 PostForm인스턴스를 생성해서 템플릿에 전달
        form = PostForm

    # GET 요청에서 무조건 실행
    # POST 요청에선 form.is_valid()를 통과 하지 못할 경우 실행
    context = {
        "form": form,
    }
    return render(request, 'post/post_form.html', context)


def post_detail(request, post_pk):
    # post = get_object_or_404(Post.objects.exclude(author__isnull=True), pk=post_pk)
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = PostCommentForm
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'post/post_detail.html', context)


@login_required
def post_delete(request, post_pk):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_pk)
        if post.author != request.user:
            raise PermissionDenied
        post.delete()
    return redirect("post:post_list")


@login_required
def comment_create(request, post_pk):
    # if not request.user.is_authenticated:
    #     return redirect('member:login')
    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_pk)
        form = PostCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            page_next = request.GET.get('next').strip()
            if page_next:
                return redirect(page_next)
        return redirect("post:post_detail", post_pk=post.pk)
    return redirect("post:post_list")


@login_required
def comment_delete(request, comment_pk):
    next_page = request.GET.get('next', '').strip()
    if request.method == 'POST':
        comment = get_object_or_404(PostComment, pk=comment_pk)
        if comment.author == request.user:
            comment.delete()
            if next_page:
                return redirect(next_page)
            return redirect('post:post_detail', post_pk=comment.post.pk)
        else:
            raise PermissionDenied('작성자가 아닙니다')


@login_required
def post_like_toggle(request, post_pk):
    if request.method == "POST":
        next_page = request.GET.get('next', '').strip()
        user = request.user
        post = get_object_or_404(Post, pk=post_pk)
        filtered_list_posts = request.user.like_posts.filter(pk=post.pk)
        if filtered_list_posts.exists():
            user.like_posts.remove(post)
        else:
            user.like_posts.add(post)
        if next_page:
            return redirect(next_page)
    return redirect('post:post_detail', post_pk=post_pk)

instagram/post/views/comment.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect

from ..forms import PostCommentForm
from ..models import Post, PostComment

__all__ = (
    'comment_create',
    'comment_delete',
)


def comment_create(request, post_pk):
    """
    로그인한 유저만 요청 가능하도록 함
    작성하는 Comment에 author정보 추가

    :param request:
    :param post_pk:
    :return:
    """
    if not request.user.is_authenticated:
        return redirect('member:login')

    # URL get parameter로 온 'post_pk'에 해당하는
    # Post instance를 'post'변수에 할당
    # 찾지못하면 404Error를 브라우저에 리턴
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        # 데이터가 바인딩된 CommentForm인스턴스를 form에 할당
        form = PostCommentForm(request.POST)
        # 유효성 검증
        if form.is_valid():
            # 통과한 경우, post에 해당하는 Comment인스턴스를 생성
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()

            # GET parameter로 'next'값이 전달되면
            # 공백을 없애고 다음에 redirect될 주소로 지정
            next = request.GET.get('next', '').strip()
            # 다음에 갈 URL (next)가 빈 문자열이 아닌 경우
            if next:
                # 해당 next url로 이동
                return redirect(next)
            # 지정되지 않으면 post_detail로 이동
            return redirect('post:post_detail', post_pk=post_pk)


def comment_delete(request, comment_pk):
    next_path = request.GET.get('next', '').strip()

    if request.method == 'POST':
        comment = get_object_or_404(PostComment, pk=comment_pk)
        if comment.author == request.user:
            comment.delete()
            if next_path:
                return redirect(next_path)
            return redirect('post:post_detail', post_pk=comment.post.pk)
        else:
            raise PermissionDenied('작성자가 아닙니다')

instagram/post/views/post.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect

from ..forms import PostForm, PostCommentForm
from ..models import Post

__all__ = (
    'post_list',
    'post_detail',
    'post_create',
    'post_delete',
    'post_like_toggle',
)


def post_list(request):
    """
    모든 Post목록을 리턴
    template은 'post/post_list.html'을 사용
    :param request:
    :return:
    """
    posts = Post.objects.all()
    comment_form = PostCommentForm()
    context = {
        'posts': posts,
        'comment_form': comment_form,
    }
    return render(request, 'post/post_list.html', context)


def post_detail(request, post_pk):
    # 해당 post의 사진을 img태그로 출력
    # 1. view작성
    #   1-1. post_pk에 해당하는 Post객체를
    #           post변수에 할당해서
    #           post라는 키로 context에 할당해서 render에 전달
    #   1-2. 템플릿은 post/post_detail.html사용

    # 2. url작성
    #   2-1. urls.py에 '/post/<post_pk>/에 해당하는 url에 이 view를 연결

    # 3. 템플릿 작성
    #   3-1. post/post_detail.html을 생성, 전달받은 'post'변수의
    #       photo필드의 url속성을 이용해 img태그 출력

    # 4. base템플릿 작성 및 'extend'템플릿태그 사용
    #   html:5 emmet을 사용, 기본이 되는 base.html을 작성, 나머지 템플릿에서 해당 템플릿을 extend
    #   내용은 'content' block에 채운다
    # post = Post.objects.get(pk=post_pk)
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = PostCommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'post/post_detail.html', context)


@login_required
def post_create(request):
    """
    1. 이 뷰에 접근할 때, 해당 사용자가 인증된 상태가 아니면 로그인 뷰로 redirect
        is_authenticated

    2. form.is_valid()를 통과한 후, 생성하는 Post객체에 author정보를 추가
        request.user

    :param request:
    :return:
    """
    if not request.user.is_authenticated:
        return redirect('member:login')

    if request.method == 'POST':
        # POST요청의 경우 PostForm인스턴스 생성과정에서 request.POST, request.FILES를 사용
        form = PostForm(request.POST, request.FILES)
        # form생성과정에서 전달된 데이터들이 Form의 모든 field들에 유효한지 검사
        if form.is_valid():
            # 유효할 경우 Post인스턴스를 생성 및 저장

            # 1. 커스텀 메서드 사용
            # form.save(author=request.user)

            # 2. 기존 Django의 ModelForm방식 사용
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:post_list')
    else:
        # GET요청의 경우, 빈 PostForm인스턴스를 생성해서 템플릿에 전달
        form = PostForm()

    # GET요청에선 이부분이 무조건 실행
    # POST요청에선 form.is_valid()를 통과하지 못하면 이부분이 실행
    context = {
        'form': form,
    }
    return render(request, 'post/post_form.html', context)


def post_delete(request, post_pk):
    if not request.user.is_authenticated:
        return redirect('member:login')

    if request.method == 'POST':
        # post_pk에 해당하는 Post가 있는지 검사
        post = get_object_or_404(Post, pk=post_pk)
        # request.user가 Post의 author인지 검사
        if post.author == request.user:
            post.delete()
            return redirect('post:post_list')
        else:
            raise PermissionDenied('작성자가 아닙니다')


@login_required
def post_like_toggle(request, post_pk):
    """
    1. view, url연결
        /post/<post_pk>/like-toggle/

    2. 로직구현
        post_pk에 해당하는 Post가
        현재 로그인한 유저의 like_posts에 있다면 없애고
        like_posts에 없다면 추가

    3. post.html에서 현재 user가 해당 post를 like했는지 여부 표시
        {% if <A> in <B> %}

    4. post.html에서 이 뷰로 요청을 보낼 수 있는 form구현

    :param request:
    :param post_pk:
    :return:
    """
    if request.method == 'POST':
        # GET파라미터로 전달된 이동할 URL
        next_path = request.GET.get('next')

        # post_pk에 해당하는 Post객체
        post = get_object_or_404(Post, pk=post_pk)

        # 요청한 사용자
        user = request.user

        # 사용자의 like_posts목록에서 like_toggle할 Post가 있는지 확인
        filtered_like_posts = user.like_posts.filter(pk=post.pk)
        # 존재할경우, like_posts목록에서 해당 Post를 삭제
        if filtered_like_posts.exists():
            user.like_posts.remove(post)
        # 없을 경우, like_posts목록에 해당 Post를 추가
        else:
            user.like_posts.add(post)

        # 이동할 path가 존재할 경우 해당 위치로, 없을 경우 Post상세페이지로 이동
        if next_path:
            return redirect(next_path)
        return redirect('post:post_detail', post_pk=post_pk)

instagram/templates/include/form-horizontal.html
<form action="" method="POST" class="form-horizontal" enctype="multipart/form-data">
	{% csrf_token %}
	{% for field in form %}
	<div class="form-group{% if field.errors %} has-error{% endif %}">
		<label
			for="{{ field.auto_id }}"
			class="col-xs-2 control-label">
			{{ field.label }}
		</label>
		<div class="col-xs-10">
			{{ field }}
			{% if field.errors %}
				{% for error in field.errors %}
				<span class="help-block">{{ error }}</span>
				{% endfor %}
			{% endif %}
		</div>
	</div>
	{% endfor %}
	{% if form.non_field_errors %}
		{% for error in form.non_field_errors %}
		<p class="text-danger">{{ error }}</p>
		{% endfor %}
	{% endif %}
	<button class="btn btn-primary btn-block">{{ submit_text }}</button>
</form>

instagram/templates/include/post.html
<div id="post-{{ post.pk }}">
    <p class="pull-right">작성자: {{ post.author.username }}</p>
    <!-- 이미지 -->
    {% if post.photo %}
        <a href="{% url 'post:post_detail' post_pk=post.pk %}">
            <img id="img_{{ post.pk }}" src="{{ post.photo.url }}" alt="" class="img-responsive"/>
        </a>
    {% endif %}
    <!-- 사진 삭제 -->
    <form action="{% url 'post:post_delete' post_pk=post.pk %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger btn-xs" style="margin-top: 10px;">사진 삭제</button>
    </form>
    <br/>
    <!-- 좋아요 -->
        {% if request.user.is_authenticated %}
            <form action="{% url 'post:post_like_toggle' post_pk=post.pk %}?next=
                {% if post_type == 'list' %}
                    {% url 'post:post_list' %}#post-{{ post.pk }}
                {% elif post_type == 'detail' %}
                    {% url 'post:post_detail' post_pk=post.pk %}
                {% endif %}" method="post">

                    {% csrf_token %}

                    {% if post in request.user.like_posts.all %}
                        <button type="submit"><span class="glyphicon glyphicon-heart"></span></button>
                    {% else %}
                        <button type="submit"><span class="glyphicon glyphicon-heart-empty"></span></button>
                    {% endif %}
            </form>
        {% endif %}
    <!-- 댓글 출력 -->
    {% if post.comments.count %}
        <ul class="center-block" id="post-comments-{{ post.pk }}">
            {% for comment in post.comments.all %}
                <li>{{ comment.content }} -
                    <!-- 댓글 삭제 -->
                    <form action="{% url 'post:comment_delete' comment_pk=comment.pk %}?next=
                        {% if post_type == 'list' %}
                            {% url 'post:post_list' %}#post-{{ post.pk }}
                        {% elif post_type == 'detail' %}
                            {% url 'post:post_detail' post_pk=post.pk %}
                        {% endif %}"
                          method="post"
                          style="display: inline-block;">
                        {% csrf_token %}
                        <button class="btn btn-warning btn-xs">댓글 삭제</button>
                    </form>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <!-- 댓글 작성 -->
    <form action="{% url 'post:comment_create' post_pk=post.pk %}?next=
        {% if post_type == 'list' %}
            {% url 'post:post_list' %}#post-{{ post.pk }}
        {% elif post_type == 'detail' %}
            {% url 'post:post_detail' post_pk=post.pk %}
        {% endif %}"
          method="post">
        {% csrf_token %}
        {{ comment_form }}
        <button class="btn btn-primary btn-block">댓글 작성</button>
    </form>
</div>
<hr/>